### PR TITLE
Refactoring of controls.js and removal of logging, fix bug in control window

### PR DESCRIPTION
**Pull request by rikkertkoppes**
When pressing "C" a second time, the control window rendered a second set of controls. This has been fixed in this pr (3b1221d) see #40 

For the rest, these are some basic maintenance commits, no functionality is added or removed. It is just some functions that have been extracted.

### CODE REVIEW

**Comment by Jheronymus** [comment]
Please create a corresponding ticket for the bugfix and reference it here.

**Review by Jheronymus — APPROVED** [review]
Tested. Works great. Nice work on the refactoring.

**Comment by poelstra** [comment]
Although the refactorings look good, it would be better to have them as a separate pr. I would merge these as-is.

For the actual fix, I'm not sure this is the 'right' way of doing it. You don't prevent creation of the controls, you just remove the old ones.

However, this can be problematic if someone eg already prepared some text in an input box.

**Comment by rikkertkoppes** [comment]
Ok, I'll split it up and have a second look at the fix

**Pull request closed without merging**
